### PR TITLE
Use CMake macro for adding tests

### PR DESCRIPTION
**Pull request by makaimann**
This PR uses a CMake macro to make it less verbose to add a test.

### CODE REVIEW

**Review by yoni206 — APPROVED** [review]
Looks good, but i am wondering -- should the CMakelists files of the tests for the individual solvers be changed as well?

**Comment by makaimann** [comment]
Yeah that's a good idea. You're saying just make it a uniform style, right?

**Comment by yoni206** [comment]
yes. though not necessary for this PR.

**Comment by makaimann** [comment]
Sounds good, I think I will do that in a separate PR after https://github.com/makaimann/smt-switch/pull/185#pullrequestreview-609026575 is merged which adds a new test directory.

**Pull request merged**
